### ISSUE TITLE
Private Message to Tricky

### ISSUE THREAD

**Issue by hacknorris-notyetbanned** [Tricky1975/tricky1975.github.io#4]
could you maybe make a gamejolt backup? I think you should ( i write here bcos i dont have your mail). But it's good, i'll give you some time for that ;)

**Comment by hacknorris-notyetbanned** [comment]
I forgot (mention) @Tricky1975

**Comment by hacknorris-notyetbanned** [comment]
did you made it ? ( i am just asking @Tricky1975 ) if smth i can wait  but i want to know

**Comment by Tricky1975** [comment]
What do you mean with a "game jolt backup"?
If you mean I should backup the entire site plus all games stored there, then no, as I simply don't have the storage power to do that, nor can I even afford that. Do you have any idea how much data we're talking about?

When it comes to a new site which could serve as an alternative for Game Jolt, I can give it a thought, but that will require a lot of time, and I also need to get finances in order for that.

**Comment by hacknorris-notyetbanned** [comment]
no i just thought about backing up things you posted and games but bad idea for the now left my head...

**Comment by Tricky1975** [comment]
When it comes to my articles posted on Game Jolt they also appear on my tumblr account, if that's what you mean by backup.

**Comment by hacknorris-notyetbanned** [comment]
and appps all are here, yep? then okay... ( bio you should bacup :D )

**Comment by hacknorris-notyetbanned** [comment]
but as i said - now i'm busy and all bad ideas left my head

**Comment by Tricky1975** [comment]
My bio, eh... I guess so... Well, my bio was less important, and pretty specific to GJ

My games are also available on itch.io.

**Comment by hacknorris-notyetbanned** [comment]
so okay ooff

**Comment by hacknorris-notyetbanned** [comment]
btw. i'm now switching to itch ( but i need some time - i'm busy both here and in real life). btw. is it good idea to leave g.j.? i think that if they made me rly angry so... idk..

**Comment by hacknorris-notyetbanned** [comment]
![image](https://user-images.githubusercontent.com/74788012/107154765-04f22400-6975-11eb-9eb5-5b46f21ee6d8.png)

**Comment by Tricky1975** [comment]
Yeah, I guess that reply by thoro came in quite harshly, eh.... 
I already expected she would not reply nicely (if she would reply at all).
![image](https://user-images.githubusercontent.com/11202073/107155780-9d3ed780-697a-11eb-82c8-c7139eefab58.png)

Perhaps it's better if you do indeed not ask for verifications on my behalf (especially not on that tone).
Like I said, if I think I require verification I'd already have asked them myself.

**Comment by hacknorris-notyetbanned** [comment]
> Yeah, I guess that reply by thoro came in quite harshly, eh....
> I already expected she would not reply nicely (if she would reply at all).
> ![image](https://user-images.githubusercontent.com/11202073/107155780-9d3ed780-697a-11eb-82c8-c7139eefab58.png)
> 
> Perhaps it's better if you do indeed not ask for verifications on my behalf (especially not on that tone).
> Like I said, if I think I require verification I'd already have asked them myself.

what from you have it?

**Comment by hacknorris-notyetbanned** [comment]
and next thing ( for not spamming on your proflie with that ) this thing with dr. bowen uuuuummmmmmmmmm yhy ( i'll delete that for saving memory in g.j. server)

**Comment by Tricky1975** [comment]
She posted that under your request to have my GJ account verified... However that message has now been deleted, and I have the feeling she deleted your request. 

And yeah, that Dr. Bowen thing in my shoutbox was making me a bit uneasy

**Comment by hacknorris-notyetbanned** [comment]
could you look at my gamejolt? you'll be shocked. really

**Comment by Tricky1975** [comment]
Today shall be known as the day you compared Dr. Bowen to Jack Sparrow?

**Comment by hacknorris-notyetbanned** [comment]
yup :D
